version: '3.8'

services:
  kitchen_service:
    build: ./kitchenService
    ports:
      - "8080:8080"
    environment:
      - ENV=development

  order_service:
    build: ./orderService
    ports:
      - "8081:8081"
    environment:
      - ENV=development
