version: '3.8'

services:
  kitchen-service:
    build:
      context: ./kitchenService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    networks:
      - app-network

  order-service:
    build:
      context: ./orderService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
